const config = {
  month: 'Month',
  week: 'Week',
  seeAll: 'See All',
  save: 'Save',
  totalTowRequest: 'Total Tow Request',
  totalUser: 'Total Users',
  pageVisit: 'Page visits',
  socialTraffics: 'Social traffic',
  appName: 'e-Tows',
  myAccount: 'My Account',
  allUsers: 'All Users',
  importCSV: 'Import CSV',
  updateUser: 'Update User',
  uploadNow: 'Upload Now',
  activeUsers: 'Active Users',
  allJobs: 'All Service Requests',
  all: 'All',
  active: 'Active',
  pending: 'Pending',
  goToLocation: 'Go to Location',
  assign: 'Assign',
  close: 'Close',
  availableDrivers: 'On Duty Drivers',
  createDispatchRequest: 'Service Request',
  submit: 'Submit',
  createUsers: 'Create Users',
  userprofile: 'User Profile',
  map: 'Maps',
  dashbaord: 'Dashboard',
  towRequestLocation: 'Tow Request Location',
  assignJob: 'Assign Job',
  Delete: "Delete User",
  govtAgency: 'Govt Agency/Contacts',
  towVehicle: 'Tow Vehicle Inventory',
  CorporateDetails: 'Corporate Documents',
  corpDetails: 'Corporate Documents Detail',
  fleetInventory: 'Fleet Inventory',
  fleet: 'Fleet',
  staff: 'Staff',
  InsuranceInformation: 'Insurance Information',
  TowImpoundedVehicle: 'Tow/Impounded vehicle',

  police: 'Police',
  byLaw: 'By Law',
  DataPrepopulatedDriverLE: 'Data pre-populated by Tow Driver/LE',
  ByPoundAdminVehicleProperty: 'By Pound Admin - Disposition of Vehicle/Property',
  driver: "Driver",
  Otherstaff: "Other Staff",
  contact1: 'Contact1',
  contact2: 'Contact2',
};
export default config;